<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2</name>
   <tag></tag>
   <elementGuidId>3565c5b5-50b4-4747-8c59-d0dc7246a2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82e9ed42-51e6-429c-9bff-0855659f14f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root jss58 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck</value>
      <webElementGuid>803d2596-a328-4a9f-83d2-a17ae05c5b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0c004418-67ed-4276-97c6-5c2de3b1d5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7f2e391-ecb1-465c-bc9b-d0805e933217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fdd9a9b2-7ede-4a1e-a49a-046ca84217b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9479e928-87ad-4dcb-a41c-e022e38d2cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>קוראים</value>
      <webElementGuid>74faa556-4748-49f2-ba6b-dc5d25d46ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eDLJxc eKstPV&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed jss48 mui-fixed muirtl-1ozpllr&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular muirtl-i6s8oy&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container jss49 muirtl-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9 muirtl-14ybvol&quot;]/div[1]/div[@class=&quot;MuiTabs-root jss56 muirtl-2jg8vw&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed muirtl-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer muirtl-k008qs&quot;]/button[@class=&quot;MuiButtonBase-root MuiTab-root jss58 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck&quot;]</value>
      <webElementGuid>243b4662-ccb1-4a66-b46e-94a1c7b9697c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>94058e34-1b90-42cd-a1b9-73248f0458ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/div[2]/div/div/div/div/button[3]</value>
      <webElementGuid>cf717fd0-348f-4528-8fba-bef3dbe438a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>8ed03864-3633-4706-804e-39a915091722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'קוראים' or . = 'קוראים')]</value>
      <webElementGuid>d490509c-4064-4d42-9385-dd2b64c8a94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
