<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_3</name>
   <tag></tag>
   <elementGuidId>0fe441ed-0d3d-40f1-9908-aa9fe5cc62ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6551cff3-91d9-478d-89ab-ae01d38efbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root jss60 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck</value>
      <webElementGuid>3fdd457a-465b-4366-a869-553a224b602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>159d8be0-b553-4986-a17b-0113cc7e4bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db1d0979-03a4-4cfa-baba-0f5c3a0e033e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>939ace7a-58dd-48fd-b708-f58689a70857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c6783e0-8797-42a6-ae43-d5c9fc9a5c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>השאלות</value>
      <webElementGuid>3ae43a27-a397-4526-a18f-1333cb925ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-qZqnM upbzY&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed jss50 mui-fixed muirtl-1ozpllr&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular muirtl-i6s8oy&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container jss51 muirtl-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9 muirtl-14ybvol&quot;]/div[1]/div[@class=&quot;MuiTabs-root jss58 muirtl-2jg8vw&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed muirtl-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer muirtl-k008qs&quot;]/button[@class=&quot;MuiButtonBase-root MuiTab-root jss60 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck&quot;]</value>
      <webElementGuid>b73a7735-c048-4d03-985c-b4c228276f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>3515f245-e718-475f-83af-574787197228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/div[2]/div/div/div/div/button[4]</value>
      <webElementGuid>cffd3035-6042-480a-a034-167424788d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>2bc8c179-fbd8-4445-b829-c16e807e8dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'השאלות' or . = 'השאלות')]</value>
      <webElementGuid>a07a2cb9-2e35-407b-89b6-03655aa0f9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
