<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1</name>
   <tag></tag>
   <elementGuidId>c4720b1f-ea84-43ba-80d4-2874970e6832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiTab-root.jss58.MuiTab-labelIcon.MuiTab-textColorPrimary.muirtl-1cs4uck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e133e0d5-c586-4286-b415-dac961c58b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root jss58 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck</value>
      <webElementGuid>6418be48-ab73-4c15-b79c-20d243b162b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cb33abfe-8512-4cd9-ae11-6175d20b99e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3413e11c-d46f-4e7e-97ad-9dfb0a4ef2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>06e03ad7-4aba-4b4e-854e-aa23d766725b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e12f4af1-57ac-4ff4-a6d1-27fe857b7afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>פריטים</value>
      <webElementGuid>b88924e8-791c-4105-bc97-16940e9bd4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eDLJxc eKstPV&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed jss48 mui-fixed muirtl-1ozpllr&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-gutters MuiToolbar-regular muirtl-i6s8oy&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container jss49 muirtl-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9 muirtl-14ybvol&quot;]/div[1]/div[@class=&quot;MuiTabs-root jss56 muirtl-2jg8vw&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed muirtl-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer muirtl-k008qs&quot;]/button[@class=&quot;MuiButtonBase-root MuiTab-root jss58 MuiTab-labelIcon MuiTab-textColorPrimary muirtl-1cs4uck&quot;]</value>
      <webElementGuid>9d11a66a-9081-414a-a32e-2995468d84ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>4c1a1a0b-8dd8-4848-b8bd-f738e0aad417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>cfacb78b-1e6a-4c3b-87a9-de62e136eb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0f6098a6-4743-4fc3-b0d3-8b5d5590e4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'פריטים' or . = 'פריטים')]</value>
      <webElementGuid>4e31361e-a398-463c-8582-bfebe1c08f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
