<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_inside</name>
   <tag></tag>
   <elementGuidId>b43566ca-05e4-487a-ad8f-7db76907e58c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root.MuiButton-root.jss78.jss105.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.MuiButton-root.jss78.jss105.MuiButton-text.MuiButton-textPrimary.MuiButton-sizeMedium.MuiButton-textSizeMedium.muirtl-hbsh1i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b45bb01-263a-43e8-b829-b94f77de2e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root jss78 jss105 MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root jss78 jss105 MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium muirtl-hbsh1i</value>
      <webElementGuid>1e012666-e43b-4f3f-8ec3-04d3f1e9aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>217efc09-661e-4f50-90b4-36785e3a70d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f22e8a3-1409-451b-8594-d1478ba821ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>add-item</value>
      <webElementGuid>259cfd2d-6f50-4e5a-8326-0beee6ed1bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>הוספת קורא</value>
      <webElementGuid>67668e41-a979-4c1d-b591-0dd7ae52eb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fff&quot;)/div[1]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 muirtl-119yzve&quot;]/div[@class=&quot;jss91&quot;]/div[@class=&quot;jss92&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container muirtl-8p7p4d&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-4 muirtl-1udb513&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container muirtl-8p7p4d&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-6 muirtl-1s50f5r&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root jss78 jss105 MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root jss78 jss105 MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium muirtl-hbsh1i&quot;]</value>
      <webElementGuid>3dd45cbf-7add-4391-8066-74349c5b3df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>207537f3-27cb-451e-b3c0-cd382e28c1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fff']/div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>223aed5a-6c83-44d4-846c-57b952718732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>d6469431-5642-449e-a1ae-9183e8082cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'הוספת קורא' or . = 'הוספת קורא')]</value>
      <webElementGuid>7aaa159e-5c0c-478b-ad38-8e3d1b2fed67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
