<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divuniform-id_gender2</name>
   <tag></tag>
   <elementGuidId>55e4cd30-b269-450d-9bab-1bd83a18761a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uniform-id_gender2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uniform-id_gender2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90208509-49d0-4380-9f71-8ac9f17871bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>49386f58-5de5-4ef6-a35d-d58bd85feb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>71a1d21e-7ec0-409b-8fb7-145549a6cac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniform-id_gender2</value>
      <webElementGuid>144a912d-e2e8-408c-aaba-8e739d42a410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniform-id_gender2&quot;)</value>
      <webElementGuid>45e93aba-89c0-4b99-8cc4-0e6692cafeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uniform-id_gender2']</value>
      <webElementGuid>8a714744-7726-4ebd-a7ac-244fd52aedc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/div/div[2]/label/div</value>
      <webElementGuid>aab45bbd-422f-4316-958a-08dcd5ccc284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div</value>
      <webElementGuid>3c9969da-ae53-4bfc-bab7-255632783c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uniform-id_gender2']</value>
      <webElementGuid>287ca9be-b71f-43d4-b28f-5b08bea08420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
