<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Day123456789101112131415161718192021_40ab5b</name>
   <tag></tag>
   <elementGuidId>f11b9fd5-3ed2-45c0-9d63-c8791cc92e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#days</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='days']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0382727-f3ea-424e-b9d1-0573ec910a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>1d64c6dd-9576-4bf3-8b6e-47a1c04b973a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>2a74051f-f51f-4097-8620-249fe27dee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>days</value>
      <webElementGuid>e3a260a6-2383-4bb8-b3b4-e1d60dbf1ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cd035af1-f059-47f8-98d8-8f7d76671057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											</value>
      <webElementGuid>2d54d8d7-7e93-4bfd-86a0-0bcc49bd4ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;days&quot;)</value>
      <webElementGuid>76b73205-36cc-4c6f-983b-cbb466585c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='days']</value>
      <webElementGuid>ab37ff9f-6256-4b03-a1e0-54c64f2fc176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-days']/select</value>
      <webElementGuid>21832b65-fe46-4bfd-bcbd-dbefc7da27e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>982a9021-1f8c-446f-ad01-45ed23e26061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'days' and @name = 'days' and (text() = '
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											' or . = '
												Day
												1
												2
												3
												4
												5
												6
												7
												8
												9
												10
												11
												12
												13
												14
												15
												16
												17
												18
												19
												20
												21
												22
												23
												24
												25
												26
												27
												28
												29
												30
												31
											')]</value>
      <webElementGuid>e212efe5-8d5a-49d2-ab90-054a6a888ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
