<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_exit_to_app  Login</name>
   <tag></tag>
   <elementGuidId>3531b680-74c2-467d-9269-aaa7d7925618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbarLoginButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbarLoginButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f182e136-8023-4720-8812-2f27242be085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>ffbe0e53-b8d0-43f4-84fc-5df5f535bee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Go to login page</value>
      <webElementGuid>2bf00bc2-20f4-4d51-b1af-c21acff35cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarLoginButton</value>
      <webElementGuid>ba269da1-d7b5-4f18-97c1-8653ae9d18cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-item ng-tns-c129-2 ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>a7021522-c77e-46ed-9e3c-e6ef577e60e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ef366ab-d8c1-4eb3-b2cc-c0793d42eaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>301048f5-5bce-454d-ba5d-df8f447e76ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92836c48-3921-43d4-83f8-ea418cd62cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> exit_to_app  Login </value>
      <webElementGuid>96f6b1b0-5f12-4416-a14d-b9c02a1983c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarLoginButton&quot;)</value>
      <webElementGuid>36b5ace1-4062-41bd-bf01-88fb1e6ce8b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navbarLoginButton']</value>
      <webElementGuid>8fbb8a78-e6b3-4ab3-b3f4-7d728d518e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/button</value>
      <webElementGuid>a5466a2e-3259-4557-a804-1146623f83f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click for more information'])[1]/following::button[1]</value>
      <webElementGuid>7b49fb52-92b1-4ec6-9f4c-31f77fa9ffee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose language'])[1]/following::button[1]</value>
      <webElementGuid>3ad86df3-751a-40ca-926b-35df756dfa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>bc958149-72a1-4ce7-98e5-5f3687c6dd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navbarLoginButton' and (text() = ' exit_to_app  Login ' or . = ' exit_to_app  Login ')]</value>
      <webElementGuid>db789fb0-3766-4bf0-9a4a-2bef9c6b147c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
